### ISSUE TITLE
1D trial problems

### ISSUE THREAD

**Issue by antoniommateo** [trotter-suzuki-mpi/trotter-suzuki-mpi#130]
By fixing the dim_y (and related) attributes to 1, the system seems to work as an effective 1-dimensional one for the grid purposes but not the solver, since it returns nan numbers. It seems that although the grid is ok the calculation is not.

**Comment by peterwittek** [comment]
This is related to finishing the work on issue #83. @dingliu0305, any progress?

**Comment by dingliu0305** [comment]
I'm working on the 1-D kernel. Could you give us more detailed information about your problem? Which calculation returns nan numbers? @antoniommateo

**Comment by peterwittek** [comment]
We were using a small trick to force the 2D kernel to work on a 1D lattice. After creating a regular 2D square lattice, we manually set all y-axis-related spatial extensions to 1. This is what failed. Could you give an estimate when you could send a pull request with the 1D kernel? I think instead of debugging this trick, we could just focus on issues #83 and #29.

**Comment by peterwittek** [comment]
Issue #29 is now resolved. Setting the vertical grid points to 1, and length to 0, we might have the desired effect. The new syntax is

```python
import trottersuzuki as ts
n_points_x = 100
n_points_y = 1
length_x = 20.0
length_y = 0.0
grid = ts.Lattice2D(n_points_x, length_x, n_points_y, length_y)
```

Please try it.

**Comment by antoniommateo** [comment]
Great! Thank you, I'll try it

**Comment by peterwittek** [comment]
Since the 1D kernel is working, more or less, this trick is no longer worth pursuing.
