### ISSUE TITLE
Document and expose coordinate transformation

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#153]
Most helper functions center and scale the coordinates, but this is done quietly and without documentation. The coordinate transformation should be exposed to the user as a function to help, for instance, define the potential by a function in the C++ version (Python version does the transformation automatically, since it passes an array anyway). Also, the documentation should mention this transformation.

**Comment by peterwittek** [comment]
@Lucacalderaro, I need your insight. I merged PR #155, which is meant to unify coordinate transformation across the board (states, potentials, C++, Python). The transformation is this:

```python
def center_coordinates(grid, x, y):
    idy = grid.start_y * grid.delta_y + 0.5 * grid.delta_y +  y * grid.delta_y
    x_c = grid.global_no_halo_dim_x * grid.delta_x * 0.5
    y_c = grid.global_no_halo_dim_y * grid.delta_y * 0.5
    idx = grid.start_x * grid.delta_x + 0.5 * grid.delta_x +  x * grid.delta_x
    return idx - x_c, idy - y_c
```
Similarly in C++. There are two and a half things happening: scaling, centering, and a shift by 0.5*delta. We consistently did the scaling and the shift everywhere, but centering went missing in `ExponentialState`, `SinusoidState` (I can live with these two), and in the `get_value` method of `Potential`. This latter is puzzling and I changed this to do the centering too. Did you have a particular reason not to center here?

The second question: why the shift 0.5*delta? Assume you have open boundary conditions and a single process. This is the simplest scenario. In this case, I think the coordinate axes should go from -lattice_size/2 to +lattice_size/2, but we are very slightly off because of this shift.

When we use arrays (i.e., state initialization, state imprinting, potentials set with an array and not with a function), we consistently do something like this: `matrix[y, x] = whatever_function(x_r, y_r)`, where `x_r` and `y_r` are the return values of `center_coordinates`. Doesn't this mean that everything is upside down? This is problematic when the potential is defined by a function: the state is upside down, but the potential is not.

Many thanks.

**Comment by Lucacalderaro** [comment]
Nice work @peterwittek.

Well that was a bug, in the `get_value` method the centering is needed when the exponential of the external potential is initialized from a function.

I introduced a shift just to have a better sampling of the state and potential's function. Immagine to have a small 1D lattice `Lattice1D(3,3)`, with no halos so that `grid.start_x = 0` and `grid.delta_x = 1`. Then `x_c = 1.5` and the coordinate transformation reduces to `x_r = x + 0.5 - 1.5 = x - 1`. Since `x` is the index of the elements of the array grid, its values are x = 0, 1, 2, hence x_r = -1, 0, 1. So the functions are sampled simmetrically. If the shift is not present, the transformation would be `x_r = x -1.5`, hence x_r = -1.5, -0.5, 0.5, which is not a simmetric sampling. It is not something really important, since the dimension of the grid is usually large, but at least it produces plots that are centered.

Doesn't we use `matrix[y, x] = whatever_function(x_r, y_r)` for the potential as well? They should be both upside down.

We should use `center_coordinates` also in `SinusoidState` and `HarmonicPotential`. However, this does not include the case when periodic boundaries are set. I think a simple solution is to add some if statements
```
def center_coordinates(grid, x, y):
    idy = grid.start_y * grid.delta_y + 0.5 * grid.delta_y +  y * grid.delta_y
    x_c = grid.global_no_halo_dim_x * grid.delta_x * 0.5
    y_c = grid.global_no_halo_dim_y * grid.delta_y * 0.5
    idx = grid.start_x * grid.delta_x + 0.5 * grid.delta_x +  x * grid.delta_x
    if idx - x_c < -grid.length_x*0.5:
        idx += grid.length_x
    if idx - x_c > grid.length_x*0.5:
        idy -= grid.length_y
    if idy - y_c < -grid.length_y*0.5:
        idy += grid.length_y
    if idy - y_c > grid.length_y*0.5:
        idy -= grid.length_y
    return idx - x_c, idy - y_c
```

**Comment by peterwittek** [comment]
I see your point and we should keep things symmetric. Commit defa56d1d3978e109f5b0075fd662bd166343f63 adds the adjustments for periodic boundary conditions -- in principle, this should also work for multiple processes.

Yes, I think you are right about everything being upside down, but does not make it any better. We should flip the y axis.

Could you look into adding `center_coordinates` to `SinusoidState`, `ExponentialState`, and `HarmonicPotential`? Thanks.

**Comment by Lucacalderaro** [comment]
I have added `center_coordinates` to `SinusoidState`, `ExponentialState` and `HarmonicPotential`, (see commit f30a24a4fa362374f43cc129e35eee8020f1e175).

You are right, when the state matrix is printed, the state is upside down. Nevertheless, this is how python print out an array: the x index increases going from the left to the right, while the y index increases going downwards. So, to me, the way we initialize the array is correct since an increment of the index of the array's element corresponds to an increment of the physical coordinate. We may add a method to the State and Potential classes that plots the arrays in the correct way. What do you think?

**Comment by peterwittek** [comment]
Awesome. I think we can close this. If someone complains about things being upside down, we can address it separately. Many thanks.
