### ISSUE TITLE
cylindrical symmetry

### ISSUE THREAD

**Issue by pietromassignan** [trotter-suzuki-mpi/trotter-suzuki-mpi#159]
Would it be possible to implement cylindrical symmetry in the code?

**Comment by Lucacalderaro** [comment]
The definition of the quantum system with cylindrical symmetry is possible as long as we implement the cylindrical coordinates, mapping the space defined by the radial and vertical component to the 2D lattice. 
To ensure the best integration with the current code, we should restructure a bit the library to make it work with any coordinate system.
With the current code, the wave functions and Hamiltonians are defined using cartesinan coordinates and mapped to the 2D (or 1D) lattice through the function `center_coordinates`.
The change of coordinates change also the form of the operators in the Hamiltonian. Since we approximate the evolution operator as a multiplication of blocks, each one calculating the exponentiation to a particular operator, in general, there should be a block_kernel function for each operator that could appear in the Hamiltonian. Then, only certain blocks are used in the `full_step` function, depending on which coordinate system is used, to build the evolution. Also, the function that calculate the expected values should depend on the coordinate system.

The following are the basic changes I would do:

- the coordinate system should be a property of the Lattice class and specified when the Lattice is constructed.
- the function `center_coordinates` should be used with cartesian coordinates but not with cylindrical coordinates, since one of the coordinates has only positive values. We could generalize this function to work with a general coordinate system.
- the expected values should be revised:
    * the kinetic and total energies should account for the additional element in the laplacian.
    * instead of having a function for each expected value (`get_mean_x`, `get_mean_xx`, …), what if we create a single function that takes as input the string of the operator (like ‘x’, ‘x^2’, …)?
    * I think the expected value of the angular momentum, as it is currently implemented, should be omitted when dealing with cylindrical coordinates.
- the solver should be aware of the coordinate system (through the Lattice property) and it should choose the correct blocks in `full_step` (and `full_step_imaginary`) that builds the evolution operator. For the cylindrical coordinates, we only need to add a block calculating exponentiation to the additional term in the laplacian. Using some if statements we could switch from one coordinate sytem to the other.

These points are not difficult to implement and I think it could be a good starting point for an eventual extension to other coordinate systems.

**Comment by peterwittek** [comment]
I fully agree with your points. As an initial step, I did one and a half things:

1. Removed the hybrid kernel all together. The additional complexity was simply not worth it and nobody used this kernel anyway. Commit ad79b082cbae0cb269b1c49acd2d6bd80dab975a.
2. Moved out geometry-related non-class member functions from the CPU kernel to a separate file (commit c393d5ef82c531c229a830a81dc6d3fd6ddf4983). The same should be done for the GPU kernel.

With this separation, we can boldly move on to define new geometries.

**Comment by Lucacalderaro** [comment]
Perfect, should we create a new branch?

**Comment by peterwittek** [comment]
[Done](https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/tree/cylindrical).

**Comment by ChaconAlexis** [comment]
How are you planning to expand non trival Laplacian along the radial coordinate?

**Comment by Lucacalderaro** [comment]
We use the second-order approximation of the trotter-suzuki formula. With this approach, we calculate $exp(\alpha O)$, with $\alpha$ some complex constant and $O$ the operator, in the coordinate representation. Since we work with a finite space, this reduces to calculate the exponential of some matrices. See for example this issue https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/issues/158. In this particular case, we need to calculate the above formula for $O = i/\rho \partial_{\rho}$.

**Comment by Lucacalderaro** [comment]
Commits 5a0a7b6090bf4232c01df441e364a53bc93c2a6d and e563b06de3bdd6f1238e077d7ec7f73f5b0a2b59, correctly implement cylindrical coordinates in the code (for the 2D lattice).

@peterwittek, I have a couple of questions:

- As there are the classes that define particular states (GaussianState, ExponentialState, ...), I think it would be good to add the class BesselState, initializing the wave function with bessel functions of the first kind, which are the tipical solutions in cylindrical coordinates. The BOOST library include such functions. However, this would add a dependency on BOOST to compile the code. Would this be a problem?

- Regarding the Python wrapper, in commit 8ddf7daad66b84d9fe7a37b73fca4ef367660e47 all the calls to the function `center_coordinates` are preceded by a star symbol `*center_coordinates`. What is the reason for this? I had to remove the star to run the code on my Python version.

**Comment by peterwittek** [comment]
Can we conveniently copy the Bessel functions from Boost? I would rather not have it as a dependency.

It works for you after removing the asterisk? Weird. This is the scenario:

```python
def test_function(x, y):
    print(x, y)

def get_coordinates():
    return 0, 0

test_function(*get_coordinates())
```
Here `get_coordinates` returns a tuple, but `test_function` does not expect a tuple as an arguments, but two variables. The asterisk turns the tuple into its two constituents. I tried in Python 2.7 and 3.6, and both cases, I needed the asterisk.

**Comment by Lucacalderaro** [comment]
I gave a look to the included file, but I think it is too difficult to copy. Anyway, I found that math.h already include the bessel functions, but not their zeros. A not very elegant workaround could be to store the first N zeros, x_n, of the first L bessel functions (so that, J_l(x_n) = 0 with l = 0,..,L and n = 0,..,N).

Sorry, I actually removed only the asterisk in line 307 in class_extension:
`np.exp(-1j*delta_t*self.pot_function(*map_lattice_to_coordinate_space(self.grid, x, y), t))`
here the problem I think is the extra argument `t`.

**Comment by peterwittek** [comment]
Okay, if the Bessel functions can be used with a slight extension from `math.h`, that sounds much better.

Yeah, that extra `t` can mess it up.

**Comment by Lucacalderaro** [comment]
Commits e177acafc0016bfa40c2718617551e9410bf0f12 and 726dad5bfbd46cd6ac8a1df7c17afe614a1b40ab should fix these two minor issues.

**Comment by peterwittek** [comment]
Perfect!
