### ISSUE TITLE
Time-dependent potential

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#45]
This does not need changes in the kernels.

**Comment by peterwittek** [comment]
Commit 5793a87b95529c5dca1d8a5df278b91c05b7df3c allows you to do this. However, if you repeatedly call `evolve`, the potential is re-evolved from time 0. Right now the potential evolution function has four parameters: x, y, delta_t, and iteration. Perhaps it is worth adding a fifth one for time_0. This time could be internally tracked by the solver class, with no burden to the user. @Lucacalderaro, any thoughts?

**Comment by Lucacalderaro** [comment]
I think this is the way; a private parameter 'time_0' in Solver is needed for sure, but we should have the possibility to re-evolve with the potential from 0. I would say that the default behavior is the one that does not re-evolve with the potential starting from time 0.

I also think that we do not need the *external_pot pointer, we just need a pointer to a function which define the external potential, which is the new *evolve_potential (maybe with default parameters double delta_t=0, int t=0, to include definitions of static potentials). Indeed almost all the time, the external potential is defined by a function. If we had a potential defined by a matrix it would not be easy to correctly use it in the case of more than one process running, since the algorithm should split it accordingly to the sublattices of the processes. Instead, it is easier to fit it with a function and then use the function.

Also I would add some pre-defined static external potential as members of Hamiltonian. For instance the harmonic potential is the most used. In the same way, I think it is worth adding a predefined initial state as member of State; I am thinking about the gaussian-state.

**Comment by peterwittek** [comment]
Good point about not having to store the external_pot array at all. Predefined static external potentials and states could be added, but not in the classes. Since these are parametric one way or the other, perhaps tiny classes could be added. I am working on this now.

**Comment by peterwittek** [comment]
So there are three issues here:

  1. Classes for state types. This is done by 65bfc834ed42486f8df489ee3028828d97aebba6. Please adjust the Gaussian state class to be fully parametric and to make physical sence, and change the vortexes and other examples based on Gaussian states to use this class.

  2. Correct parametrization of an evolving potential. If we keep track of the physical evolution time (this is what commit 944031e04e8d1a781ca4d83641a4b9cde4881bcb), then it might be sufficient to pass this single parameter to the `evolve_potential`/`update_potential` function instead of a triplet (time0, delta_t, and iterations). Let me know what you think.

  3. The trickiest is the potential and whether it should be an array. I will have to think about it.

**Comment by Lucacalderaro** [comment]
1. Great solution!
2. I agree, maybe in Solver::evolve I would add an optional parameter to eventually reset current_evolution_time

**Comment by peterwittek** [comment]
Actually, I wanted to keep it simple: the current_evolution_time is a public variable, so it can be set to zero from the calling side.

**Comment by peterwittek** [comment]
I am creating a class structure for this to abstract away the representation of the potential.

**Comment by peterwittek** [comment]
Please take a look at commit 2477f22c6bcabe8810985da3d5f5ccbf9e3fb2db. Now we may or may not use an array to store the Hamiltonian potential. Please change the parameters of the new ParabolicPotential class to make physical sense. Once that is done, we can close this issue.
