### ISSUE TITLE
make python does not compile the module when cuda is detected

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#56]
running 'make python', object files are searched in trottersuzuki/src/ directory, but they are not found. It seems that the setup.py does not compile the sources.

**Comment by peterwittek** [comment]
The build command fails, but the install command does not. This is because the `MyInstall` class which does the compilation is only called in the install target. Since the only purpose of `make python` is to prepare the Python folder with the subfolders prepared and the source files copied, I don't think this is a bug.

If we really want to fix it, we need to figure how to call external compilation from the build target.

**Comment by Lucacalderaro** [comment]
Do you mean 'make python_install' works? I am having the same problem also with it (I am having this problem, since I installed CUDA on my system).

**Comment by peterwittek** [comment]
Actually, I meant `python setup.py install`. The make target `python_install` depends on the `python` and `python_doc` targets, so it is bound to fail. As a matter of fact, the `python_doc` target does not exist. I think the best is to remove the `python_install` target.

**Comment by peterwittek** [comment]
Commit 90a63bb5eb09020422f051b9d9f577c234e3f096 should fix it.

**Comment by Lucacalderaro** [comment]
Ok, now ```python_install``` works, thanks.
