### ISSUE TITLE
Efficient calculation of norms and expectation values

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#82]
The expensive part of calculating individual bits of the different energy expectation values is the loop over the elements of the state (and sometimes the potential). The norm calculation does the same thing. The ``Solver`` class could have a single function to calculate all of these values (both the norm2 and the energy expectation values) if any of them is requested. This function would have a single loop over the (x, y) of the state(s) and the potential. The loop is easily parallelized with an OpenMP pragma.

The overhead of calculating all of them at once compared to a single calculation is negligible. Then the class would save them and return the saved value if another of them is asked for. 

The values would be invalidated at each state update, like it is currently done with the norm2. Additionally, the ``Solver`` class could have a ``calculate_squared_norm(int which)`` method, since it keeps track of the norm2 anyway.

**Comment by Lucacalderaro** [comment]
I think that's the best solution, but I would rather define a private parameter, e.g. `<bool expected_values_updated>`, instead of changing the norm to a negative value. Indeed the norm is needed when calculating the imaginary time evolution.

**Comment by peterwittek** [comment]
Sure, it makes more sense.

**Comment by Lucacalderaro** [comment]
The total energy value is biased from the true value due to the algorithm that calculate the kinetic energy value -- the potential energy is correct. The finite second order approximation of the kinetic operator is not very accurate. We could try with a higher order of approximation or we could use Fourier transformation to get the state on the momentum basis (this should be the most accurate algorithm, but also the least efficient).

**Comment by peterwittek** [comment]
As in higher-order TS approximation? My concern is that it would make the kernels even more complicated, and I would rather not introduce further complexity until the GPU kernel reaches feature parity. Furthermore, it would increase computational cost in each iteration.

On the other hand, we only read out the expectation values every now and then, so we could accept a bit of overhead. We do not have to do the Fourier transform ourselves either. CUDA comes with its own mathematical libraries, including an FFT implementation (similarly, CuBLAS calls are already used in calculating the norm the imaginary time evolution on the GPU). For the CPU kernel, we could introduce [fftw](http://www.fftw.org) as a dependency, which already uses AVX and OpenMP for speed.

**Comment by peterwittek** [comment]
Fourier transformation being a global operation, we have to take special care in the MPI version, but [fftw works with MPI](http://www.fftw.org/doc/2d-MPI-example.html#g_t2d-MPI-example). I am not sure about CuFFT.

**Comment by Lucacalderaro** [comment]
We do not need to touch the evolution kernel, that is accurate. 

What I meant was to improve the approximation in calculating the integrals for the kinetic energy, in particular the [approximation](https://en.wikipedia.org/wiki/Finite_difference) used to discretize the energy operator, which is a second derivative in space.

Commit 6ee19d576109dd846fc75b33a18533f4f9ad6ced close this issue, improving the approximation of the kinetic energy from second order to fourth order, and the approximation for the momentum from first order to third order. This guarantees a much more accurate calculation of energies and momenta. In the example code `harmonic_osc_real.cpp`, the deviation of the calculated potential energy from the theoretical value is of the order of 10^-15 (for a 256x256 grid), since the potential operator is already diagonal it does not have to be approximated, so this minor error is given by the discretization of the integral into a sum over the points of the grid. As regard the kinetic energy, the deviation from the theoretical value is of the order of 10^-7 (for a 256x256 grid) with the last commit, while before that it was of the order of 10^-4.

I guess that if we adopt FFT for the kinetic energy calculation we could reach almost a deviation of the same order of the potential energy, since a FFT on the state diagonalize the kinetic energy operator. 

However, for the moment I am happy with the fourth order approximation for the kinetic operator.

**Comment by peterwittek** [comment]
This was beautifully executed. The only thing I would change is the calculation of the norm2. Since we only need it in the end of the expectation value calculations, we could calculate it together with the rest of the values, hence we would loop over the state(s) only once.

**Comment by Lucacalderaro** [comment]
Your right! I'll do that thanks.

Il giorno ven 15 gen 2016, 12:32 Peter Wittek <notifications@github.com> ha
scritto:

**Comment by peterwittek** [comment]
There are two more things that could improve speed:

1. Apart from the norm2 calculation, the two nested for loops in ``Solver::calculate_energy_expected_values`` could be merged with a reasonable effort.

2. Once it is done, a single OpenMP pragma would parallelize the loop (see l. 197 in ``model.cpp``).

**Comment by Lucacalderaro** [comment]
The latest commits fix these points. Please check if commit 38efab41226e9255071d070851cfbfce0a3ed906 correctly implement the OpenMP pragma reduction.

**Comment by peterwittek** [comment]
Wow, this is awesome. The overall logic looks good.
